Repository SalesforceFoundation/OutboundFundsModule, pull requests merged in 2021-02, with the labels that each got.

#80 [W-8828011] Latest Definition of Done
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in dev review, no QE needed, 🎯 this sprint

#83 [W-8857319] - Fixing hardcoded string reference that prevent label audit to pass
  force-app/main/default/aura/disbursementsCreate/disbursementsCreateHelper.js
Labels: in dev review, 🎯 this sprint

#82 [W-8791351] - Create Disbursements component permissions
  force-app/main/default/aura/disbursementsCreate/disbursementsCreate.cmp
  force-app/main/default/aura/disbursementsCreate/disbursementsCreateController.js
  force-app/main/default/aura/disbursementsCreate/disbursementsCreateHelper.js
  force-app/main/default/classes/controllers/disbursementsCreate/disbursementsCreateController.cls
  force-app/main/default/classes/controllers/disbursementsCreate/disbursementsCreateController.cls-meta.xml
  force-app/main/default/classes/controllers/disbursementsCreate/tests/disbursementsCreateController_TEST.cls
  force-app/main/default/classes/controllers/disbursementsCreate/tests/disbursementsCreateController_TEST.cls-meta.xml
  force-app/main/default/classes/disbursementsCreateController_TEST.cls
  force-app/main/default/classes/selectors/FundingRequestSelector.cls
  force-app/main/default/classes/selectors/FundingRequestSelector.cls-meta.xml
  force-app/main/default/classes/selectors/tests/FundingRequestSelector_TEST.cls
  force-app/main/default/classes/selectors/tests/FundingRequestSelector_TEST.cls-meta.xml
  force-app/main/default/classes/services/DatabaseService.cls
  force-app/main/default/classes/services/DatabaseService.cls-meta.xml
  force-app/main/default/classes/services/tests/DatabaseService_TEST.cls
  force-app/main/default/classes/services/tests/DatabaseService_TEST.cls-meta.xml
  force-app/main/default/classes/testUtils/TestUser.cls
  force-app/main/default/classes/testUtils/TestUser.cls-meta.xml
  force-app/main/default/classes/testUtils/UnitTest.cls
  force-app/main/default/classes/testUtils/UnitTest.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
Labels: Child Branch, 🎯 this sprint
