Repository SalesforceFoundation/OutboundFundsModule, pull requests merged in 2021-05, with the labels that each got.

#119 W-9185738 - Modify columns to Recently Viewed, All, and Related Lists for Review object
  force-app/main/default/objects/Review__c/Review__c.object-meta.xml
  force-app/main/default/objects/Review__c/listViews/All.listView-meta.xml
Labels: ready for QE, 🎯 this sprint

#117 W-9025988 - Submit Review record
  cumulusci.yml
  datasets/mapping.yml
  datasets/sample.sql
  force-app/main/default/layouts/Review__c-Review Layout.layout-meta.xml
  force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
  force-app/main/default/objects/Review__c/fields/SubmittedDate__c.field-meta.xml
  force-app/main/default/quickActions/Review__c.SubmitReview.quickAction-meta.xml
Labels: 🎯 this sprint

#122 W-9202379 - Update Description for Unscheduled Disbursements Report
  force-app/main/default/reports/NPSP_Outbound_Fund_Reports/Unscheduled_Disbursements.report-meta.xml
Labels: no QE needed, 🎯 this sprint

#123 W-925119: Update Open Reviews listview to include 'Submitted'
  force-app/main/default/objects/Review__c/listViews/OpenReviews.listView-meta.xml
Labels: ready for QE, 🎯 this sprint

#127 [Robot] Submit a Review as Test User
  robot/OutboundFunds/doc/Keywords.html
  robot/OutboundFunds/resources/ContactPageObject.py
  robot/OutboundFunds/resources/OutboundFunds.py
  robot/OutboundFunds/resources/OutboundFunds.robot
  robot/OutboundFunds/resources/ReviewPageObject.py
  robot/OutboundFunds/resources/locators_52.py
  robot/OutboundFunds/resources/qa_org/users/perms_test_user.json
  robot/OutboundFunds/resources/unpackaged/qa/package.xml
  robot/OutboundFunds/resources/unpackaged/qa/permissionsets/SubmitReview.permissionset-meta.xml
  robot/OutboundFunds/tests/browser/Review/Review.robot
  robot/OutboundFunds/tests/browser/Review/SubmitReview.robot
  robot/OutboundFunds/tests/standard_objects/create_contact.robot
Labels: robot test 🤖

#130 W-9270679 - Yarn update for Dependabot issues
  yarn.lock
Labels: no QE needed, 🎯 this sprint

#132 W-9200006 - Update storytelling data
  datasets/mapping.yml
  datasets/sample.sql
Labels: 🎯 this sprint
