Repository SalesforceFoundation/OutboundFundsModule, pull requests merged in 2021-03, with the labels that each got.

#85 [W-8885817] OFM: Automerge major release branches
  cumulusci.yml
Labels: no QE needed, ready to merge; waiting for merge freeze 🧊🧊🧊, 🎯 this sprint

#89 Robot - Setup for OutboundFunds Robot Tests
  cumulusci.yml
  robot/OutboundFunds/doc/Keywords.html
  robot/OutboundFunds/resources/BaseObjects.py
  robot/OutboundFunds/resources/FundingProgramPageObject.py
  robot/OutboundFunds/resources/FundingRequestPageObject.py
  robot/OutboundFunds/resources/OutboundFunds.py
  robot/OutboundFunds/resources/OutboundFunds.robot
  robot/OutboundFunds/resources/locators_50.py
  robot/OutboundFunds/resources/locators_51.py
  robot/OutboundFunds/tests/OutboundFunds.robot
  robot/OutboundFunds/tests/browser/Disbursements/Disbursements.robot
  robot/OutboundFunds/tests/browser/FundingProgram/FundingProgram.robot
  robot/OutboundFunds/tests/browser/FundingRequest/FundingRequest.robot
  robot/OutboundFunds/tests/browser/Requirements/Requirements.robot
Labels: needs RE review :lock:, robot test 🤖

#91 W-8950994 - OFM: 230 sandbox push upgrade failures - remove flexipage report references
  cumulusci.yml
  force-app/main/default/flexipages/Funding_Program_Record_Page.flexipage-meta.xml
  lib/admin.profile-meta.xml
Labels: 🎯 this sprint

#88 [W-8903763] Support Platform Encryption: Removed SOQL Filters
  force-app/main/default/classes/controllers/disbursementsCreate/tests/disbursementsCreateController_TEST.cls
  force-app/main/default/classes/services/tests/DatabaseService_TEST.cls
Labels: no QE needed

#97 [Robot] fixing robot lint warnings and errors
  robot/OutboundFunds/resources/OutboundFunds.py
  robot/OutboundFunds/resources/OutboundFunds.robot
  robot/OutboundFunds/tests/browser/Disbursements/Disbursements.robot
  robot/OutboundFunds/tests/browser/FundingProgram/FundingProgram.robot
  robot/OutboundFunds/tests/browser/FundingRequest/FundingRequest.robot
  robot/OutboundFunds/tests/browser/Requirements/Requirements.robot
  robot/OutboundFunds/tests/standard_objects/create_contact.robot
Labels: robot test 🤖

#100 Adds namespace tokens to unmanaged references
  unpackaged/qa/permissionsets/Disbursements.permissionset-meta.xml
Labels: Child Branch

#99 [Robot] Disbursement permission test
  cumulusci.yml
  robot/OutboundFunds/resources/qa_org/users/perms_test_user.json
  robot/OutboundFunds/resources/unpackaged/qa/package.xml
  robot/OutboundFunds/resources/unpackaged/qa/permissionsets/Disbursements.permissionset-meta.xml
  robot/OutboundFunds/tests/browser/Disbursements/DisbursementPermissions.robot
Labels: robot test 🤖
